### ISSUE TITLE
Semantics: Countdown timers should not be buttons

### ISSUE THREAD

**Issue by swordfischer** [SteamLUG/steamlug.org#116]
As per #96.

Either add `disabled` to the button element, or find an alternative way of formatting.

**Comment by Cheeseness** [comment]
I think understanding the rationale behind making them buttons is an important first step to working out how to deal with it. Can you speak more about why you make the decision to make them have button like behaviour?

**Comment by swordfischer** [comment]
I just chose something that resembled the current look, which is the pagination/button style

**Comment by Cheeseness** [comment]
Ah, OK. If the behaviour wasn't intentional, then we can just get rid of that and pick something that isn't button related and/or write our own styles for it.

**Comment by johndrinkwater** [comment]
How is this looking now? It still needs style work, but no longer actually buttons to bootstrap.

**Comment by Cheeseness** [comment]
Yeah, sweet. Thanks for doing that. Agree that it still needs a bit of tweaking (eg: it's referencing Orbitron but we're not yet defining that, and there's probably some stuff we can do to make it fit a bit nicer with the rest of the style)

**Comment by Cheeseness** [comment]
As mentioned here, I made a couple of small changes. I don't think it's quite there, but it's closer maybe? Thoughts?

**Comment by johndrinkwater** [comment]
It still needs tweaking, c/p what I put on IRC: hmm, if it were me, I would make the labels the same appearance and just put them as :, maybe put days on another line, I dunno

**Comment by Cheeseness** [comment]
Yeah, replacing the current label text with colons felt like it was the nicest option I could come up with without making markup changes.

**Comment by johndrinkwater** [comment]
Either way, this issue is resolved as far as I can see, it is a button no more. Thanks @swordfischer !
