### ISSUE TITLE
Finish youtube thumbnailer

### ISSUE THREAD

**Issue by johndrinkwater** [SteamLUG/steamlug.org#120]
This is stuck on getting more data into the notes: game developer name / handle and their avatars, and a list of games we are discussing (steam appid).

**Comment by johndrinkwater** [comment]
https://github.com/SteamLUG/steamlugcast-shownotes/commit/22d14d20d3535acdd4ba2b8e30e8417c8d23dd51 adds developer avatar + game info. Thoughts?

**Comment by Cheeseness** [comment]
Looks OK to me. I agree that we should probably have a different name for guest specific topic thumbnails/URLs.

**Comment by johndrinkwater** [comment]
Some of the tweaks are live on staging atm, but waiting on the notes to be synced before they will reflect any change.

Playing around with how we could display the cast list now, want to refer to the hosts less formally than their twitter handle, but how? This grabs forename, but for some (like psychonic) their alias/handle should be chosen?
![screenshot 2015-01-12 003332](https://cloud.githubusercontent.com/assets/7708/5697802/5bc2fb2c-99f3-11e4-9c38-a5109dbef237.png)

**Comment by johndrinkwater** [comment]
https://github.com/SteamLUG/steamlug.org/commit/39bdeb2e851878467feb279dc4f5e54240cb2cbe should make this bug closable, rest of tweaks to ship this on the site (renaming a notes variable?) is waiting on #121 now.

**Comment by johndrinkwater** [comment]
Another thing to help get the youtube process smooth-as, https://github.com/SteamLUG/steamlug.org/blob/master/youtubedescription.php will auto-generate a compact description from the show notes. Like the above work, it is reliant on the new shownotes repo being on the server
