### ISSUE TITLE
Host transcriberer on the site

### ISSUE THREAD

**Issue by johndrinkwater** [SteamLUG/steamlug.org#122]
Not too important, but we can have it populate the current cast to transcribe, and set the default note contents to include our header block to make it easier.

**Comment by johndrinkwater** [comment]
Things it can do for us: compute the FILENAME, SEASON, EPISODE and DURATION fields, pre-populate PUBLISH with the current date, then add our common headings after the data.

**Comment by Cheeseness** [comment]
I had wanted to implement some kind of POST support for Transcriberer. That could be helpful here as well.

**Comment by johndrinkwater** [comment]
This is now here https://github.com/SteamLUG/transcriberer
What’s the best way to get it on the site, is a submodule in https://github.com/SteamLUG/steamlug.org/ a good idea?

**Comment by johndrinkwater** [comment]
bump.

**Comment by johndrinkwater** [comment]
This needs a tweak to the webhook; so will need to wait for #124 to be completed.

**Comment by Cheeseness** [comment]
Sounds good. In the meantime, people can clone and run it locally.

**Comment by johndrinkwater** [comment]
This was resolved with #132 being pulled in, closing.
