### ISSUE TITLE
Find another website host

### ISSUE THREAD

**Issue by swordfischer** [SteamLUG/steamlug.org#124]
As of 1st of April, cenobite will no longer host any steamlug related material.

**Comment by Cheeseness** [comment]
In the interests of making the site more portable, we should reduce reliance on absolute paths and non-steamlug.org domains (if we do need absolute paths, then they should probably be moved out to vars that can be included from a siteconfig.php or similar).

cenobite.swordfischer.com references:
* news.php
* steameventparser.php

/var/www/dev.steamlug.org references:
* creds.php
* servers.php

/var/www/archive.steamlug.org references:
* youtubethumb.php
* youtubedescription.php
* cast.php

/var/www/steamlug.org references:
* feed/calendar.php
* feed/cast.php
* giveaway.php

I also grabbed [a couple](https://gist.github.com/Cheeseness/8c42449e2970375ab7d5) of the supporting scripts/files that I know about (would appreciate pointers to any others). I feel like we should probably be hosting the server list on github, and it wouldn't hurt to have generic versions of steamlug.php and cronjab in the wiki or something.

**Comment by johndrinkwater** [comment]
The shownotes repo should clear up the /var/www/archive.steamlug.org dependency - that location will then only contain audio files for download, not the episode.txt files.

**Comment by Cheeseness** [comment]
Something I haven't grabbed is a dump of the DB. It's probably worth holding off on that until the current poll has run its course though (end of the month).

**Comment by johndrinkwater** [comment]
Remaining work is sorting out the references to cenobite.swordfischer.com, as our cronjob and event parsing still abuse that.

**Comment by johndrinkwater** [comment]
Our steamlug cast shownotes refer to these files as well, make sure to grab a copy:
http://archive.steamlug.org/steamlugcast/steamlug_intro.ogg
http://archive.steamlug.org/steamlugcast/steamlug_outro.ogg
https://archive.steamlug.org/SteamLUG_-_SOTMC_Jingle.mp3
http://archive.steamlug.org/AutoSave_WineCellar_2013_5_15_19_47_59_0.sav

**Comment by johndrinkwater** [comment]
Current progress: this is nearly complete, event XML is correctly cronjob’d up on new server.
@Corben78, would you mind grabbing the files in the above comment and putting them on the server

**Comment by Corben78** [comment]
steamlug_intro.ogg and steamlug_outro.ogg are not found.
The two other files are grabbed.

**Comment by Cheeseness** [comment]
Try the outro URL again now. Not having luck finding steamlug_intro.ogg, but I have a local .flac version.

**Comment by johndrinkwater** [comment]
This is now resolved, closing :)
