### ISSUE TITLE
Site needs a favicon

### ISSUE THREAD

**Issue by johndrinkwater** [SteamLUG/steamlug.org#128]
Noticed while messing around with feeds that browsers still look for /favicon.ico by default, so let us put something small there, and set our headers to a better quality png.

I have zero artistic skill, so defer this work ;)

Would be nice to have something vector so we can export at various qualities - homepage/touch icons are p common so add that in the process.

**Comment by Cheeseness** [comment]
After doing a couple of polls (like the current one) geared towards getting more of the community taking part in them, I was going to run a poll on logo stuff so that we could settle on something with community input.

Can a favicon wait till then?

**Comment by johndrinkwater** [comment]
A favicon can wait til the end of the earth. No rush.

**Comment by Cheeseness** [comment]
Another thought - perhaps in the meantime, we could use an image that was just filled solid with the "SteamLUG blue" as a placeholder until we get more "branding" type stuff nailed down?

**Comment by johndrinkwater** [comment]
Sure, OK.

**Comment by johndrinkwater** [comment]
https://github.com/SteamLUG/steamlug.org/commit/45ff712cb0824370185390a0ff452183a8dd86b0 is that SteamLUG blue placeholder.

**Comment by Cheeseness** [comment]
Cheers!

**Comment by Corben78** [comment]
Site has a favicon.
Also an apple-touch-icon.
Using cheeseness' cool stencil tux as template.
