### ISSUE TITLE
Create serverlist repo?

### ISSUE THREAD

**Issue by johndrinkwater** [SteamLUG/steamlug.org#129]
We probably don’t wish to maintain that file with the server software, and yet still track changes so we don’t lose them.
Having some history may help with transparency too, people would need to *commit* their own servers, if you can excuse the pun.

Downsides to this?

**Comment by Cheeseness** [comment]
I would've popped it in the main repo, but if it's not, maybe it should be part of a more generalised configuration repo that we can eventually bust out SteamLUG type branding/etc. to to allow the site to be more generic for any other groups that would be interested in forking?

**Comment by johndrinkwater** [comment]
Made this https://github.com/SteamLUG/steamlug-gaming-servers aiming to let server owners have commit access so they can manage their commitments how they see fit. Add on a commit hook and its another thing we don’t have to manually juggle.

Not sure many groups would consider forking us, but with the recent work on getting it ready for a new server, it is in better shape to.
