### ISSUE TITLE
Cache guest avatars on server

### ISSUE THREAD

**Issue by johndrinkwater** [SteamLUG/steamlug.org#130]
Need some way to automatically store a twitter handle / steam avatar on our server without messing around with FTP or doing things manually.
Can always get cast.php to pull down an avatar on first seeing a handle, but that might be problematic.

Suggestions?

**Comment by xPaw** [comment]
You can use avatars from their Steam profiles (have them login on the website, so it gets stored in the database).

**Comment by johndrinkwater** [comment]
mhm, that was the plan until bumping into a devs reluctant to share their steamid, which I can sympathize with.

**Comment by Cheeseness** [comment]
I'd lean towards caching Steam avatars and using Gravatar as a fallback. I vaguely recall some discussion where somebody didn't like the idea of relying on Gravatar though.

Another use case where Steam avatars aren't appropriate is people who represent a larger organisation and don't want to be seen as an individual (was it Edwin that wanted us to use the official Feral Twitter account as the guest link instead of his personal one?).

**Comment by johndrinkwater** [comment]
Would supporting Steam avatars, and allowing file uploads (only for getAdmins() accounts) be enough? Think I have an OK system in my head to let us give out one-time use urls to our guests, if they choose the steam auth option.

**Comment by Cheeseness** [comment]
Sure, if you think it works/is worth the effort. Gravatar support still feels like it might be worth implementing since it's so widespread.

**Comment by johndrinkwater** [comment]
https://github.com/SteamLUG/steamlug.org/commit/d882d978ed0183c1b3488df179acb157cbff9955 adds Gravatar and Steam avatar caching, though it requires admins to grant permission, making a temporary token that you can share with a user, eg https://staging.steamlug.org/avatar/?name=example&key=e2dbaf2b9a8036706f0ae394bf0ad24d
Otherwise, admins can visit the page, grant/revoke tokens, remove avatars and fetch them from email addresses.

It currently cannot delete files because that is commented out, and cannot write files because:
* server needs config to be able to read & write to two locations
* one publically accessible location for the image files
* one private location for the tokens + log

Uploaded files should be exposed at /avatars/name.png (gotta pick an ext for cast files)

If you’re unhappy that it uses files for tokens, you can swap that out for db if that’s your preference.

**Comment by johndrinkwater** [comment]
This was resolved with #132 being pulled in, closing.
