### ISSUE TITLE
Integrate youtube player for the cast videos on the news page

### ISSUE THREAD

**Issue by Corben78** [SteamLUG/steamlug.org#165]
As Twitter and the Steam announcement page can inlcude the youtube player, the SteamLUG news page should include it, too.

**Comment by johndrinkwater** [comment]
As I mentioned on mumble, related to https://github.com/SteamLUG/steamlug.org/issues/63 for content parsing.

**Comment by johndrinkwater** [comment]
This is complete as of https://github.com/SteamLUG/steamlug.org/commit/cf7c4617030a1972eebc9e31285a95cb39a3e384 and will be integrated with #174
