### ISSUE TITLE
Work on the privacy policy

### ISSUE THREAD

**Issue by johndrinkwater** [SteamLUG/steamlug.org#170]
With commit 0893546d5c we now have a linkable page to inform our members of what we store, why we store, how they can ask us to store more(!) and how they can be forgotten. 

Would like people to comment on phrasing, whether it adequately covers everything we keep, and if it is substantial enough.
Feedback very welcome.

**Comment by beansmyname** [comment]
I see nothing wrong with the verbiage used. The policy identifies what data is retrieved from Steam, what data is stored on the site and for how long. It also provides explanation on opting out of data use.

**Comment by johndrinkwater** [comment]
Added a bit about what we keep if you delete your account. Is this complete?

**Comment by johndrinkwater** [comment]
Complete with the #174 merge
