### ISSUE TITLE
Server page shows German servers as Russian

### ISSUE THREAD

**Issue by her001** [SteamLUG/steamlug.org#178]
https://steamlug.org/servers

Has been happening for a while now, right?

**Comment by johndrinkwater** [comment]
Yup, a while

**Comment by JasonRivers** [comment]
This is possibly a GEOIP issue on the server - how up to date is the geoip package? When I run the site locally it's all fine.

**Comment by johndrinkwater** [comment]
That is the very issue, yeah. Has been since moving to @Corben78 servers and last I asked about it, they were the latest available. It is likely we have to install something out of band ;)

**Comment by Corben78** [comment]
Updated geoip-database package from 20130213-1 to 20150209-1.
Flags (especially german ones) are now shown correct.
