### ISSUE TITLE
Goal of projects page

### ISSUE THREAD

**Issue by beansmyname** [SteamLUG/steamlug.org#182]
Curious about the intended purpose of the projects.php page. Is it meant to highlight projects by the SteamLUG.org team or projects being worked on by members of the Steam for Linux community?

**Comment by Cheeseness** [comment]
I can't speak to any current plans, but my original intention was that it would be for community projects (Haunt, etc.) as well as site features that were stable enough for broader use, but not ready for integration (like the polling system which would've been integrated on every page as part of a site-wide layout change).

**Comment by beansmyname** [comment]
Thank you for the explanation.
