### ISSUE TITLE
Menu Redesign/Prioritizing

### ISSUE THREAD

**Issue by swordfischer** [SteamLUG/steamlug.org#29]
Currently we have:

News | Chat (IRC, Mumble) | Group *external link* | Gaming (Events, Servers, Live Stream) | Projects (Overview, SteamLUG Cast) | About

It is likely that other people work through menus as I do when not going for anything specific, which means I'll open from the left to the right. When I click Group it will leave the site. I don't like that.

Furthermore, the more prominent features of the SteamLUG website is 'hidden away' more or less. Here I'm talking about the Cast, Events and Servers.
News | Cast | Events | Servers | Mumble | Live Stream | About

I'd rather get rid of the Group button, and have a flavourful ribbon or something that indicates the viewer will be taken to steamcommunity.com instead.
Also, removing the webchat seems like an obvious move, considering nobody uses it.

To me the menu takes up too much of the site, is clunky and unintuitive.

I know we have talked about a 'site redesign' but we might as well separate it as much as possible to create a better overview.

**Comment by johndrinkwater** [comment]
We worked on this a while ago, and the menu could probably have another redesign (Projects menu is kinda pointless atm), but that is for future consideration so closing as complete.
