### ISSUE TITLE
Implement Twitter Card Support

### ISSUE THREAD

**Issue by Cheeseness** [SteamLUG/steamlug.org#69]
I've noticed for a couple of other things that I'm involved with that implementing Twitter cards has had a pretty noticeable impact on Twitter presence.

Summary cards are super easy to do, but player cards (something I haven't yet tried myself) might be interesting to explore in that they'd potentially allow us to embed casts into tweets.

https://dev.twitter.com/docs/cards/validation/validator
https://dev.twitter.com/docs/cards/types/player-card

Thoughts?

**Comment by johndrinkwater** [comment]
Have requested approval for steamlug.org domain

**Comment by johndrinkwater** [comment]
This is done for /cast/, but i’d like to look into it for events…

**Comment by johndrinkwater** [comment]
Going to close this as Twitter Card support was added for casts many months ago, the planned events/user pages have still not arrived and I imagine if they ever do, this issue can be replicated or reopened.
